config/routes.rb
Reconnecting::Application.routes.draw do

  devise_for :admins
  match '/', to: 'static_pages#home', via: :get
  match 'demonstration', to: 'static_pages#demonstration', via: :get
  match 'contact-us', to: 'static_pages#contact_us', via: :get
  match 'strategy', to: 'static_pages#strategy', via: :get
  match 'how-it-works', to: 'static_pages#how', via: :get


  resources :admins, only: [:index, :show, :destroy]
  match 'admins/confirm', to: 'admins#confirm', via: [:put, :patch]


  resources :categories


  resources :resources


  resources :pathways
  match 'pathways/:id/questions', to: 'pathways#questions',
        as: :pathway_questions_order, via: :get
  # resources :pathways do
  #   resources :questions do
  #     resources :answers
  #   end
  # end


  resources :questions
  namespace :ux do
    resources :questions, only: :show
    get 'final', to: 'questions#final'
    get 'remotebutton', to: 'questions#remote_button'
  end

  resources :answers

  # added per devise instructions
  root to: 'static_pages#home'

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :pathway
  has_many :answers, dependent: :destroy

  accepts_nested_attributes_for :answers, reject_if: lambda {|a| a[:text].blank?}, allow_destroy: true

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  layout 'admin'

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.select('questions.*')
                         .joins(:pathway)
                         .order('pathways.name, questions.order')
                         .all
    @question = Question.new

    @pathways = Pathway.order(:name).all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @questions }
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = Question.includes(:answers, :pathway).find(params[:id])
    @query = request.query_parameters
    @query[:p] ||= ''

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/new
  # GET /questions/new.json
  def new
    @question = Question.new
    @pathways = Pathway.order(:name)
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/1/edit
  def edit
    @question = Question.includes(:answers).find(params[:id])
    @parent_pathway = Pathway.find(@question.pathway_id)
    @pathways = Pathway.order(:name)
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(permitted_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.js   {}
        format.json { render json: @question, status: :created, location: @question }
      else
        format.html { render action: "new" }
        format.js   {}
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.json
  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(permitted_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.js   {}
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.js   {}
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url }
      format.js   {}
      format.json { head :no_content }
    end
  end

private

  def permitted_params
    params[:question].permit(:text,
                             :order,
                             :pathway_id,
                             answers_attributes: [:id,
                                                  :text,
                                                  :end_of_path,
                                                  :pathway_id,
                                                  :_destroy])
  end

end

app/controllers/ux/questions_controller.rb
class Ux::QuestionsController < ApplicationController
  skip_before_filter :authenticate_admin!

  def show
    @question = Question.includes(:answers, :pathway).find(params[:id])
    @path_taken = path_taken

    begin
      @reassurance = Answer.find(@path_taken.last).reassurance if @path_taken.last.present?
    rescue ActiveRecord::RecordNotFound
      Rails.logger.info "Answer not found for id# #{@path_taken.last}"
      Rails.logger.info "Request: #{request.original_url}"
    end

    @resources = Resource.find_for @path_taken
  end

  def final
    @path_taken = path_taken
    @resources = Resource.find_for @path_taken
  end

  def remote_button
    render 'ux/remote/button', layout:false
  end

private

  def path_taken
    @p ||= (request.query_parameters[:p] || '').split ','
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/ux/questions/_privacy.html.haml
.row-fluid#privacy-notice
  .span12.white
    %p 
      %span.bold Privacy Note:
      All answers you provide are retained only for the current session. You will not be asked for any personally identifying information while using this tool, and your answers will not be tied to any profile or login you may have on any site.

app/views/ux/questions/final.html.haml
.row-fluid
  .span12.white
    - if @resources.count > 0
      %h2 Here are the resources we've found for you
      .row-fluid
        .span12
          %h2 Resources
          %ul#resources.final
            = render @resources.slice(0,5)
    - else
      %h1 The system is currently undergoing maintenance.  Please try again later.

app/views/ux/questions/show.html.haml
.row-fluid
  .span8.white
    %h2= @question.text
    - @question.answers.each do |answer|
      - path_taken = (@path_taken + [answer.id.to_s]).join(',')
      - if answer.end_of_path
        = link_to answer.text, "#{ux_final_path}?p=#{path_taken}", class: 'btn btn-answer'
      - else
        - next_question = answer.next_question(@path_taken)
        - if next_question.present?
          - url = "#{ux_question_path(next_question)}?p=#{path_taken}"
          = link_to answer.text, url, class: 'btn btn-answer'
        - elsif admin_signed_in?
          = link_to answer.text, edit_answer_path(answer), class: 'btn btn-answer path-error'

  .span4
    .row-fluid
      .span12.white
        %h2 Resources
        - if @resources.count > 0
          %ul#resources
            = render @resources
    - if @reassurance.present?
      .row-fluid
        .span12.blue
          %p= @reassurance