config/routes.rb
Reconnecting::Application.routes.draw do

  devise_for :admins
  match '/', to: 'static_pages#home', via: :get
  match 'demonstration', to: 'static_pages#demonstration', via: :get
  match 'contact-us', to: 'static_pages#contact_us', via: :get
  match 'strategy', to: 'static_pages#strategy', via: :get
  match 'how-it-works', to: 'static_pages#how', via: :get


  resources :admins, only: [:index, :show, :destroy]
  match 'admins/confirm', to: 'admins#confirm', via: [:put, :patch]


  resources :categories


  resources :resources


  resources :pathways
  match 'pathways/:id/questions', to: 'pathways#questions',
        as: :pathway_questions_order, via: :get
  # resources :pathways do
  #   resources :questions do
  #     resources :answers
  #   end
  # end


  resources :questions
  namespace :ux do
    resources :questions, only: :show
    get 'final', to: 'questions#final'
    get 'remotebutton', to: 'questions#remote_button'
  end

  resources :answers

  # added per devise instructions
  root to: 'static_pages#home'

end

app/models/pathway.rb
class Pathway < ActiveRecord::Base

  has_many :questions, -> { order :order }, dependent: :destroy

  accepts_nested_attributes_for :questions, :reject_if => lambda { |a| a[:text].blank? }, :allow_destroy => true

  def questions_order
    questions.map {|q| q.id.to_s }
             .join ','
  end

  def questions_order=(order_list)
    order_list.split(',').each_with_index do |id, ix|
      n = questions.find_index {|q| q.id == id.to_i}
      questions[n].order = ix+1 unless n.nil?
    end
  end

private

  validates_associated :questions

end

app/controllers/pathways_controller.rb
class PathwaysController < ApplicationController
  layout 'admin'

  # GET /pathways
  # GET /pathways.json
  def index

    begin
      @pathways = Pathway.order(:name).to_a

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @pathways }
      end
    rescue
      handle_unspecified_error
    end

  end

  # GET /pathways/1
  # GET /pathways/1.json
  def show

    begin
      @pathway = Pathway.find(params[:id])

      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @pathway }
      end
    rescue ActiveRecord::RecordNotFound
      handle_pathway_not_found
    end

  end

  # GET /pathways/new
  # GET /pathways/new.json
  def new
    begin
      @pathway = Pathway.new
      @pathways = Pathway.all.collect{ |rc| [rc.name, rc.id]}
      @resources = Resource.all.collect{ |rc| [rc.name, rc.id]}
    rescue
      handle_unspecified_error
    end
  end

  # GET /pathways/1/edit
  def edit
    begin
      @pathway = Pathway.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      handle_pathway_not_found
    end
  end

  # POST /pathways
  # POST /pathways.json
  def create
    begin
      @pathway = Pathway.new(pathway_params)
      respond_to do |format|
        if @pathway.save
          format.html { redirect_to @pathway, notice: 'Pathway was successfully created.' }
          format.js   {}
          format.json { render json: @pathway, status: :created, location: @pathway }
        else
          format.html { render action: "new" }
          format.js   {}
          format.json { render json: @pathway.errors, status: :unprocessable_entity }
        end
      end
    rescue
      handle_unspecified_error
    end
  end

  # PUT /pathways/1
  # PUT /pathways/1.json
  def update

    begin
      @pathway = Pathway.includes(:questions).find(params[:id])

      respond_to do |format|
        if @pathway.update_attributes(pathway_params)
          format.html { redirect_to @pathway, notice: 'Pathway was successfully updated.' }
          format.js   {}
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.js   {}
          format.json { render json: @pathway.errors, status: :unprocessable_entity }
        end
      end

    rescue ActiveRecord::RecordNotFound
      handle_pathway_not_found
    end

  end

  # DELETE /pathways/1
  # DELETE /pathways/1.json
  def destroy

    begin
      @pathway = Pathway.find(params[:id])

      @pathway.destroy

      respond_to do |format|
        format.html { redirect_to pathways_url, notice: 'Pathway was successfully deleted.' }
        format.js   {}
        format.json { head :no_content }
      end

    rescue ActiveRecord::RecordNotFound
      handle_pathway_not_found
    end

  end

  # GET /pathways/1/questions
  def questions

    begin
      @pathway = Pathway.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      handle_pathway_not_found
    end

  end

private

  def pathway_params
    params.require(:pathway).permit(:name,
                                    :questions_order,
                                    questions_attributes: [
                                      :id,
                                      :text,
                                      :pathway_id,
                                      :order,
                                      :_destroy,
                                      answers_attributes: [
                                        :id,
                                        :text,
                                        :reassurance,
                                        :question_id,
                                        :resource_id,
                                        :pathway_id,
                                        :_destroy ]
                                      ]
                                    )
  end

  def handle_pathway_not_found
    redirect_to pathways_path, alert: 'Pathway was not found.'
  end

  def handle_unspecified_error
    Rails.logger.error "ERROR: #{$!}"
    redirect_to root_path, alert: 'Something horrible has happened.'
  end

end

app/helpers/pathways_helper.rb
module PathwaysHelper
end

app/views/pathways/_action_fields.html.haml
.action.row-fluid
  .span3
    = f.label :text, 'Action Text'
    = f.text_field :text
  .span3
    = f.label :goto_pathway, 'Go to Pathway'
    = f.select :goto_pathway, options_for_select([['This Pathway', @pathway.id]]+@pathways)
  .span3
    = f.label :connected_resource
    = f.select :connected_resource, options_for_select(@resources)
  .span3  
    = link_to_remove_fields "remove", f

app/views/pathways/_answer_fields.html.haml
.action.row-fluid
  .span3
    = f.label :text, 'Answer Text'
    = f.text_field :text
  .span3
    = f.label :goto_pathway, 'Go to Pathway'
    = f.select :goto_pathway, options_for_select([['This Pathway', @pathway.id]]+@pathways)
  .span3
    = f.label :connected_resource
    = f.select :connected_resource, options_for_select(@resources)
  .span3  
    = link_to_remove_fields "remove", f

app/views/pathways/_form.html.haml
= form_for(@pathway, remote: true) do |f|
  - if @pathway.errors.any?
    #error_explanation
      %h2= "#{pluralize(@pathway.errors.count, "error")} prohibited this pathway from being saved:"
      %ul
        - @pathway.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/pathways/_megaform.html.haml
= form_for(@pathway, remote: true, html: {class: 'form-horizontal'}) do |pf|
  .pathway
    .row-fluid.pathway-fields
      .span12
        .control-group
          = pf.label :name, class: 'control-label'
          .controls
            = pf.text_field :name

    = render partial: 'megaform_questions', locals: {pf: pf}

    .row-fluid.add-question-button
      .span12
        %button.add_question.btn.btn-mini(type='button') Add Question
        = pf.submit 'Save Pathway', class: 'btn btn-primary'

app/views/pathways/_megaform_answers.html.haml
.answers
  - qf.object.answers.build
  = qf.fields_for :answers do |af|
    - if af.object.present? && af.object.new_record?
      .answer.template
        .row-fluid
          .offset-half.span11
            .control-group
              = af.label :text, 'Answer', class: 'control-label answers_attributes'
              .controls
                = af.text_field :text, class: 'answers_attributes'
                %button.remove_answer.btn.btn-danger.btn-mini(type='button')
                  %b &times;
            .control-group
              = af.label :reassurance, class: 'control-label answers_attributes'
              .controls
                = af.text_area :reassurance, class: 'answers_attributes'
    - else
      .answer
        .row-fluid
          .offset-half.span9
            .control-group
              = af.label :text, 'Answer', class: 'control-label answers_attributes'
              .controls
                = af.text_field :text, class: 'answers_attributes'
            .control-group
              = af.label :reassurance, class: 'control-label answers_attributes'
              .controls
                = af.text_area :reassurance, class: 'answers_attributes'
          .span2
            .control-group
              = af.label :_destroy, 'Remove:', class: 'control-label answers_attributes'
              .controls
                = af.check_box :_destroy, class: 'answers_attributes'

app/views/pathways/_question_fields.html.haml
.question.row-fluid
  .span1
    = link_to_remove_fields "remove", f
  .span10
    .row-fluid
      %fieldset
        %legend
          %h3 Question
          = f.text_area :text, {rows: 2, placeholder: 'Type the question'}
          = f.label :order do
            Order of Question
            = f.number_field :order
    .actions.row-fluid
      .span12
        %fieldset
          %legend
            Answers
            = f.fields_for :answers do |builder|
              = render 'action_fields', f: builder
            = link_to_add_fields "Add Answers", f, :answers

app/views/pathways/create.js.erb
(function($pathways){

  if ($pathways.size() > 0) {
    $('<%= escape_javascript(render @pathway) %>').addClass('unsorted').appendTo('#pathways');
    $('#pathways > .pathway').detach().sort(function(a,b) {
      return $(a).find('td.sortby').text() > $(b).find('td.sortby').text()
    }).appendTo('#pathways');
    $('#pathways > .pathway').removeClass('unsorted');
    $('#notice').text('Resource pathway was successfully created.')
    $('.pathway').find('.question:not(.template)').remove()
    $('#pathway_name').val('');
  }
  else
  {
    window.location.assign("<%= pathway_path(@pathway) %>");
  }

}).call(this, $('tbody#pathways'));

app/views/pathways/destroy.js.erb
$('tr.pathway_<%= @pathway.id %>').remove();
$('#notice').text('Pathway was successfully deleted.')

app/views/pathways/edit.html.haml
.row-fluid
  .span12.white
    .row-fluid
      .span9
        %h2 Editing pathway
      .span3
        = link_to 'Show', @pathway, {class: 'btn btn-primary'}
        = link_to 'Back', pathways_path, {class: 'btn btn-secondary'}
    = render 'megaform'

app/views/pathways/index.html.haml
.row-fluid
  .span12.white
    %table(border=true)
      %thead
        %tr
          %th Pathway
          %th Actions
          %th Question
          %th Answer
          %th Goto pathway
          %th UX
      %tbody
        - @pathways.each do |pathway|
          - if pathway.questions.count > 0
            - new_pathway = true
            - p_rows = pathway.questions.reduce(0) {|tot, q| tot += [q.answers.count, 1].max }
            - pathway.questions.each do |question|
              - if question.answers.count > 0
                - new_question = true
                - q_rows = [question.answers.count, 1].max
                - question.answers.each do |answer|
                  %tr{class: "pathway_#{pathway.id}"}
                    - if new_pathway
                      %td{rowspan: p_rows}
                        = link_to pathway.name, pathway
                      %td{rowspan: p_rows}
                        = link_to 'Edit', edit_pathway_path(pathway), class: 'btn btn-mini'
                        = link_to 'Destroy', pathway, method: :delete, remote: true, data: { confirm: 'Are you sure?' }, class: 'btn btn-mini'
                      - new_pathway = false
                    - if new_question
                      %td{rowspan: q_rows}
                        = link_to question.text, question
                        (
                        = link_to 'ux', ux_question_path(question), target: '_blank'
                        )
                      - new_question = false
                    %td= link_to answer.text, answer
                    %td
                      - if answer.end_of_path
                        %button.btn.btn-mini.btn-danger.disabled end of path
                      - elsif answer.goto_pathway.present?
                        = answer.goto_pathway.name
                      - else
                        (return to previous)
                    %td
                      - if answer.end_of_path
                        = link_to 'Final', "#{ux_final_path}?p=#{answer.id}", target: '_blank'
                      - else
                        = link_to 'Next', "#{ux_question_path(answer.next_question)}?p=#{answer.id}", target: '_blank' if answer.next_question.present?
              - else
                %tr{class: "pathway_#{pathway.id}"}
                  - if new_pathway
                    %td{rowspan: p_rows}= link_to pathway.name, pathway
                    %td{rowspan: p_rows}
                      = link_to 'Edit', edit_pathway_path(pathway), class: 'btn btn-mini'
                      = link_to 'Destroy', pathway, method: :delete, remote: true, data: { confirm: 'Are you sure?' }, class: 'btn btn-mini'
                    - new_pathway = false
                  %td= link_to question.text, question
                  %td
                  %td
                  %td
          - else
            %tr{class: "pathway_#{pathway.id}"}
              %td= link_to pathway.name, pathway
              %td
                = link_to 'Destroy', pathway, method: :delete, remote: true, data: { confirm: 'Are you sure?' }, class: 'btn btn-mini'
                = link_to 'Edit', edit_pathway_path(pathway), class: 'btn btn-mini'
              %td
              %td
              %td
              %td

%br

.row-fluid
  .span12.white
    = link_to 'New', new_pathway_path, class: 'btn btn-mini'

app/views/pathways/new.html.haml
.row-fluid
  .span12.white
    %h4 Create a Pathway
    = render 'megaform'

app/views/pathways/questions.html.haml
.row-fluid
  .span12
    %h4
      Reordering questions for
      %i= @pathway.name

.row-fluid
  .span12
    %ol#questions-order
      - @pathway.questions.each do |question|
        %li.ui-state-default{id: question.id}
          .sortable-question= question.text

.row-fluid
  .span12
    = form_for @pathway do |f|
      = f.hidden_field :questions_order
      = f.submit 'Update Pathway', id: 'submit-questions-order'

app/views/pathways/show.html.haml
.row-fluid
  .span6
    .row-fluid
      .span12
        %h4 Pathway
      .offset1.span11
        = @pathway.name

    .row-fluid
      .span12
        = link_to 'Edit', edit_pathway_path(@pathway), class: 'btn btn-small'
        = link_to 'Destroy', @pathway, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-small'

  .span6
    %h4= "Questions for #{@pathway.name}"

    - needs_ordering = @pathway.questions.find_index {|q| q.order.nil? }
    - content_for :update_order_button do
      = link_to 'Update', pathway_questions_order_path(@pathway), class: 'btn btn-mini btn-warning'

    %p= link_to 'Update Ordering', pathway_questions_order_path(@pathway), class: 'btn btn-mini'

    %table(border=true)
      %thead
        %tr
          %th Question
          %th Order
      %tbody#questions
        = render partial: @pathway.questions

app/views/pathways/update.js.erb
window.location.assign("<%= pathway_path(@pathway) %>");