config/routes.rb
Reconnecting::Application.routes.draw do

  devise_for :admins
  match '/', to: 'static_pages#home', via: :get
  match 'demonstration', to: 'static_pages#demonstration', via: :get
  match 'contact-us', to: 'static_pages#contact_us', via: :get
  match 'strategy', to: 'static_pages#strategy', via: :get
  match 'how-it-works', to: 'static_pages#how', via: :get


  resources :admins, only: [:index, :show, :destroy]
  match 'admins/confirm', to: 'admins#confirm', via: [:put, :patch]


  resources :categories


  resources :resources


  resources :pathways
  match 'pathways/:id/questions', to: 'pathways#questions',
        as: :pathway_questions_order, via: :get
  # resources :pathways do
  #   resources :questions do
  #     resources :answers
  #   end
  # end


  resources :questions
  namespace :ux do
    resources :questions, only: :show
    get 'final', to: 'questions#final'
    get 'remotebutton', to: 'questions#remote_button'
  end

  resources :answers

  # added per devise instructions
  root to: 'static_pages#home'

end

app/views/resources/_form.html.haml
- disabled ||= false
= form_for(@resource, remote: true) do |f|
  - if @resource.errors.any?
    #error_explanation
      %h2= "#{pluralize(@resource.errors.count, "error")} prohibited this resource from being saved:"
      %ul
        - @resource.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    = f.text_field :name, class: "resource_attribute", disabled: disabled
  .field
    = f.label :description
    = f.text_field :description, class: "resource_attribute", disabled: disabled
  .field
    = f.label :link
    = f.text_field :link, class: "resource_attribute", disabled: disabled
  .field
    = f.label :starting_weight
    = f.number_field :starting_weight, class: "resource_attribute", disabled: disabled
  .field
    - if @category.present?
      = f.hidden_field :category_id, value: @category.id
    - else
      - selected = ['', nil]
      - selected = [@resource.category.name, @resource.category.id] if @resource.category.present?
      = f.label :category
      = f.select :category_id, options_for_select(@categories.collect{ |rc| [rc.name, rc.id]}, selected), { include_blank: true }, class: "resource_attribute", disabled: disabled
  .actions
    - if disabled
      = link_to 'Edit', edit_resource_path(@resource), class: 'btn'
    - else
      = f.submit 'Save', class: 'btn'

app/views/resources/_new.html.haml
/ TODO: Seems to be cruft.  Delete if possible.
= form_for(@resource, remote: true) do |f|
  %table(border=true)
    %thead
      %tr
        %th Name
        %th Description
        %th Link
        %th Starting Weight
        %th Actions
    %tbody
      %tr
        %td= f.text_field :name, class: "resource_attribute"
        %td= f.text_field :description, class: "resource_attribute"
        %td= f.text_field :link, class: "resource_attribute"
        %td= f.number_field :starting_weight, class: "resource_attribute"
        - if @category.present?
          %td.category
            = link_to @category.name, @category
            = f.hidden_field :category_id, value: @category.id
        - else
          - selected = ['', nil]
          - selected = [@resource.category.name, @resource.category.id] if @resource.category.present?
          %td.category= f.select :category_id, options_for_select(@categories.collect{ |rc| [rc.name, rc.id]}, selected), { include_blank: true }, class: "resource_attribute"
        %td
          = f.submit 'Save', class: 'btn'

app/views/resources/_resource.html.haml
%tr.resource{id: "resource_#{resource.id}"}
  %td.sortby= link_to resource.name, resource
  %td= resource.description
  %td= resource.link
  %td= resource.starting_weight
  %td.category= link_to resource.category.name, resource.category if resource.category.present?
  %td
    = link_to 'Edit', edit_resource_path(resource)
    = link_to 'Destroy', resource, method: :delete, remote: true, data: { confirm: 'Are you sure?' }

app/views/resources/create.js.erb
$('<%= escape_javascript(render partial: @resource) %>').addClass('unsorted').appendTo('#resources');
$('.resource').detach().sort(function(a,b) {
  return $(a).find('td.sortby').text() > $(b).find('td.sortby').text()
}).appendTo('#resources');
$('.resource').removeClass('unsorted');
$('#notice').text('Resource was successfully created.')
$('.resource_attribute').val('');

app/views/resources/destroy.js.erb
$('#resource_<%= @resource.id %>').remove();
$('#notice').text('Resource was successfully deleted.')

app/views/resources/edit.html.haml
.row-fluid
  .span12
    %p#notice= notice

.row-fluid
  .span6.white
    .row-fluid
      .span6
        %h4 Editing resource
      .span6
        = link_to 'Resource', @resource, {class: 'btn'}
        - if @resource.category_id.present?
          = link_to 'Category', @resource.category, {class: 'btn'}
        = link_to 'Resources', resources_path, {class: 'btn'}

.row-fluid
  .span6
    = render partial: 'form', locals: {remote: true}

app/views/resources/index.html.haml
.row-fluid
  .span12
    %p#notice= notice

.row-fluid
  .span8.white
    %h4 Listing resources
    %table(border=true)
      %thead
        %tr
          %th Name
          %th Description
          %th Link
          %th Starting Weight
          %th Category
          %th Actions
      %tbody{id: "resources"}
        = render partial: @resources
  .span4.white
    %h4 Add a new resource
    = render partial: 'form'

app/views/resources/new.html.haml
%h1 New resource

= render 'form'

= link_to 'Resources', resources_path

app/views/resources/show.html.haml
.row-fluid
  .span12
    %p#notice= notice

.row-fluid
  .span6.white
    .row-fluid
      .span6
        %h4 Resource
      .span6
        = link_to 'Resources', resources_path, {class: 'btn'}
        = link_to 'Category', @resource.category, {class: 'btn'}

.row-fluid
  .span12
    = render partial: 'form', locals: {disabled: true}

app/views/resources/update.js.erb
window.location.assign("<%= resource_path(@resource) %>");