config/routes.rb
Reconnecting::Application.routes.draw do

  devise_for :admins
  match '/', to: 'static_pages#home', via: :get
  match 'demonstration', to: 'static_pages#demonstration', via: :get
  match 'contact-us', to: 'static_pages#contact_us', via: :get
  match 'strategy', to: 'static_pages#strategy', via: :get
  match 'how-it-works', to: 'static_pages#how', via: :get


  resources :admins, only: [:index, :show, :destroy]
  match 'admins/confirm', to: 'admins#confirm', via: [:put, :patch]


  resources :categories


  resources :resources


  resources :pathways
  match 'pathways/:id/questions', to: 'pathways#questions',
        as: :pathway_questions_order, via: :get
  # resources :pathways do
  #   resources :questions do
  #     resources :answers
  #   end
  # end


  resources :questions
  namespace :ux do
    resources :questions, only: :show
    get 'final', to: 'questions#final'
    get 'remotebutton', to: 'questions#remote_button'
  end

  resources :answers

  # added per devise instructions
  root to: 'static_pages#home'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :resources

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  layout 'admin'

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.order(:name).all
    @category = Category.new

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])
    @resources = Resource.where(category_id: @category.id).order(:name).all
    @resource = Resource.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: { category: @category, resources: @resources } }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category].permit(:name))

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Resource category was successfully created.' }
        format.js   {}
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category].permit(:name))
        format.html { redirect_to @category, notice: 'Resource category was successfully updated.' }
        format.js   {}
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.js   {}
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.js   {}
      format.json { head :no_content }
    end
  end
end

app/views/categories/_category.html.haml
%tr.category{id: "category_#{category.id}"}
  %td.sortby= link_to category.name, category
  %td
    = link_to 'Edit', edit_category_path(category)
    = link_to 'Destroy', category, method: :delete, remote: true, data: { confirm: 'Are you sure?' }

app/views/categories/_form.html.haml
= form_for(@category, remote: true) do |f|
  - if @category.errors.any?
    #error_explanation
      %h2= "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
      %ul
        - @category.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name do
      %b Name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/categories/create.js.erb
$('.category').removeClass('just-created');
$('<%= escape_javascript(render @category) %>').addClass('unsorted just-created').appendTo('#categories');
$('.category').detach().sort(function(a,b) {
  return $(a).find('td.sortby').text() > $(b).find('td.sortby').text() 
}).appendTo('#categories');
$('.category').removeClass('unsorted');
$('#notice').text('Resource category was successfully created.')
$('#category_name').val('');

app/views/categories/destroy.js.erb
$('#category_<%= @category.id %>').remove();
$('#notice').text('Resource category was successfully deleted.')

app/views/categories/edit.html.haml
%h4 Editing category

= render 'form'

= link_to 'Show', @category

= link_to 'Back', categories_path

app/views/categories/index.html.haml
.row-fluid
  .span12
    %p#notice= notice
.row-fluid
  .span6.white
    %h4 Listing categories

    %table(border=true)
      %thead
        %tr
          %th Name
          %th Actions
      %tbody#categories
        - @categories.each do |category|
          = render partial: category
  .span6.white
    %h4 Add new category:
    = render partial: 'form'

app/views/categories/new.html.haml
%h1 New category

= render 'form'

= link_to 'Back', categories_path

app/views/categories/show.html.haml
.row-fluid
  .span12
    %p#notice= notice

.row-fluid
  .span6
    %h4= "Category: #{@category.name}"

    %div
      %span= link_to 'Edit', edit_category_path(@category)
      \|
      %span= link_to 'Back', categories_path

    %h4
      Resources for
      %i= @category.name

    %table(border=true)
      %thead
        %tr
          %th Name
          %th Description
          %th Link
          %th Starting Weight
          %th Actions
      %tbody.category#resources
        - @resources.each do |resource|
          = render resource

  .span6
    %h4 Add a new resource
    = render partial: 'resources/form'

app/views/categories/update.js.erb
window.location.assign("<%= category_path(@category) %>");